version: '2'

tasks:
  embed_assets:
    deps: [build_and_prep_ui]
    cmds:
      - go-bindata -o assets/assets.gen.go -pkg assets -prefix assets/ assets/static/...
      - git add assets/
      - git commit -m "[embed_assets] {{.BUILD_TIME}}"
    vars:
      BUILD_TIME:
        sh: echo $(date +%F_%H-%M-%S)

    silent: true
  embed_templates:
    cmds:
      - go-bindata -o templates/templates.gen.go -pkg templates -prefix templates/data templates/data/...
      - git add templates/
      - git commit -m "[embed_templates] {{.BUILD_TIME}}"
    silent: true
    vars:
      BUILD_TIME:
        sh: echo $(date +%F_%H-%M-%S)

  build_ui:
    dir: ui/
    cmds:
      - yarn build
    silent: true
  build_and_prep_ui:
    deps: [build_ui]
    silent: true
    cmds:
      - rm -r assets/static && mkdir assets/static
      - cp -r ui/dist/ assets/static/

  build:
    vars:
      BUILD_HASH:
        sh: git rev-parse --short  HEAD
      BUILD_TIME:
        sh: echo $(date +%F_%H-%M-%S)
      BUILD_TAG:
        sh: git describe --tags
    cmds:
      - go build -ldflags="-X main.commit={{.BUILD_HASH}} -X main.date={{.BUILD_TIME}} -X main.version={{.BUILD_TAG}}"