driver: postgres
db_conn: postgres://postgres:postgres@localhost/postgres?sslmode=disable
port: 8000
secret: HMAC jwt secret, use env vars instead of this
host: http://localhost:8000
minio:
  endpoint: /minio/endpoin
  access_key: minio
  access_secret: secret
nsq:
  lookupd: /nsqlookupd/endpoint
  nsqd: ""
